version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: yohan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
