version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: yohan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    ports:
      - '5432:5432'
